// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZZFN6lLC12gXXEbcXjSke_J77SM0-xaA',
    appId: '1:105736690014:web:6f39d0034d73f2daf597cf',
    messagingSenderId: '105736690014',
    projectId: 'wellness-app-188c8',
    authDomain: 'wellness-app-188c8.firebaseapp.com',
    storageBucket: 'wellness-app-188c8.firebasestorage.app',
    measurementId: 'G-YR0NDZV52X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLosSH5ULZVgGH1IYYMEMi6iaV_HpgvnQ',
    appId: '1:105736690014:android:4bca4f725d87bfe2f597cf',
    messagingSenderId: '105736690014',
    projectId: 'wellness-app-188c8',
    storageBucket: 'wellness-app-188c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADiL2SNHKlH5r0LkvTFzY84nSKpciFmW0',
    appId: '1:105736690014:ios:2a0c17d2502b8c3ff597cf',
    messagingSenderId: '105736690014',
    projectId: 'wellness-app-188c8',
    storageBucket: 'wellness-app-188c8.firebasestorage.app',
    iosBundleId: 'com.example.resetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADiL2SNHKlH5r0LkvTFzY84nSKpciFmW0',
    appId: '1:105736690014:ios:2a0c17d2502b8c3ff597cf',
    messagingSenderId: '105736690014',
    projectId: 'wellness-app-188c8',
    storageBucket: 'wellness-app-188c8.firebasestorage.app',
    iosBundleId: 'com.example.resetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZZFN6lLC12gXXEbcXjSke_J77SM0-xaA',
    appId: '1:105736690014:web:e7289be82225175ff597cf',
    messagingSenderId: '105736690014',
    projectId: 'wellness-app-188c8',
    authDomain: 'wellness-app-188c8.firebaseapp.com',
    storageBucket: 'wellness-app-188c8.firebasestorage.app',
    measurementId: 'G-8QX8RC09HH',
  );
}
